# Generated by Django 5.2.7 on 2025-10-30 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_footballer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=255)),
                ('ranking', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='footballer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footballers', to='students.team'),
        ),
    ]
