# Generated by Django 5.2.7 on 2025-10-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_team_footballer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel2/'),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footballers', to='students.team'),
        ),
    ]
