# Generated by Django 5.2.7 on 2025-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_footballer_image_alter_footballer_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballer',
            name='image',
        ),
        migrations.AddField(
            model_name='footballer',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
