# Generated by Django 5.2.7 on 2025-11-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nationality',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footballers', to='students.nationality'),
        ),
    ]
