# Generated by Django 5.2.7 on 2025-11-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_team_nationality_alter_footballer_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='nationality',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
